export const sampleCourse = {
  meta: { id: 'robots-work', title: 'Роботы работают', description: 'Семь коротких уроков о безопасной организации ИИ-агентов для одного процесса студии.', language: 'ru', checkedOn: '2026-08-31' },
  lessons: [
    {
      id: 'choose-process', slug: 'choose-process', title: 'Не строим роботов зря',
      outcome: 'Ты создашь Process Passport: цель, вход, выход, базовую точку, KPI, риск и границу решения человека.',
      retrieval: 'Стартовый урок: какая повторяющаяся задача студии действительно нуждается в описании?',
      lifeExample: { body: 'Перед сменой администратор не автоматизирует всю студию, а выбирает одну задачу: собрать внутреннюю справку из разрешённых материалов. Как мастер сначала выбирает один эскиз, так и здесь выбирают один ограниченный процесс.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Агент — рабочее определение курса: программа получает задачу, выбирает следующий шаг и действует в заданных границах. Это не универсальный научный консенсус. Сначала спроси, достаточно ли чек-листа; агент нужен только там, где есть ограниченный выбор по правилам.' },
        { heading: 'Граница безопасности', body: 'Практика использует Studio Intelligence Brief: чтение разрешённых публичных или подготовленных материалов и черновик внутренней справки. Никаких сообщений, рекламы, CRM, записи, платежей, сайта или удаления данных.' },
      ],
      practice: ['Сделай за 30 минут: заполни Process Passport из семи полей: цель, вход, выход, базовая точка, KPI, риск, граница человека.', 'Если неясны вход, владелец или риск, поставь REVIEW_REQUIRED, а не придумывай детали.'],
      artifactChecklist: ['В паспорте один процесс, а не все задачи студии.', 'KPI наблюдаем рядом с базовой точкой: минуты, доля справок с источниками или возвраты.', 'Граница оставляет результат внутренним черновиком без внешних прав.'],
      quiz: { question: 'Когда стоит остановиться и оставить REVIEW_REQUIRED?', answers: [{ id: 'unknown-owner', text: 'Когда неясны вход, владелец или риск процесса.', correct: true }, { id: 'more-agents', text: 'Когда хочется сразу добавить больше роботов.', correct: false }] },
      nextStep: 'Завтра разложи процесс на роли; пока не добавляй инструменты и доступы.', sourceIds: ['openai-agent-guide', 'anthropic-effective-agents', 'nist-ai-rmf'],
    },
    {
      id: 'map-roles', slug: 'map-roles', title: 'Организация, а не толпа',
      outcome: 'Ты нарисуешь роль-карту: Coordinator → Specialist → QA → Approval/Archive.',
      retrieval: 'Вспомни Process Passport: какая в нём одна цель и человеческая граница?',
      lifeExample: { body: 'На смене администратор принимает запрос, мастер делает узкую часть, коллега проверяет, а владелец подтверждает рискованное действие. Если все делают всё, ответственного не найти. У роботов так же.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Организация агентов — не «много роботов», а маршрут между узкими ролями. Coordinator разбирает задачу; Specialist ищет разрешённые факты; QA сверяет черновик с правилами; Approval/Archive готовит запрос владельцу или сохраняет внутренний итог.' },
        { heading: 'Начни с малого', body: 'Несколько ролей не делают систему лучше автоматически. Сначала достаточно одного ограниченного агента или чек-листа. Новую роль добавляют только после измеренного сбоя, например когда в трёх пробах смешались поиск и проверка.' },
      ],
      practice: ['Сделай за 30 минут: нарисуй четыре карточки ролей и стрелки Coordinator → Specialist → QA → Approval/Archive.', 'На каждой карточке запиши одно действие и один запрет.'],
      artifactChecklist: ['У роли одна основная ответственность, не «делать всё».', 'QA не повторяет Specialist, а проверяет доказательства и правила.', 'Последняя стрелка ведёт только к внутреннему отчёту, архиву или APPROVAL_REQUEST.'],
      quiz: { question: 'Что оправдывает добавление новой роли?', answers: [{ id: 'measured-failure', text: 'Измеренный повторяющийся сбой, который узкая роль может предотвратить.', correct: true }, { id: 'impressive-diagram', text: 'Желание сделать схему сложнее.', correct: false }] },
      nextStep: 'Завтра преврати роли в договоры: что каждая получает, возвращает и когда останавливается.', sourceIds: ['anthropic-effective-agents', 'openai-orchestration', 'anthropic-multi-agent'],
    },
    {
      id: 'define-contracts', slug: 'define-contracts', title: 'Договоры между роботами',
      outcome: 'Ты составишь три карточки ролей и route table для normal, missing-data и external-action.',
      retrieval: 'Вспомни роль-карту: кто проверяет доказательства, а кто готовит запрос владельцу?',
      lifeExample: { body: 'Бумажная передача между ресепшеном, мастером и администратором работает, когда видно, что пришло, чего не хватает и кому передать дальше. Фраза «разберитесь» — не договор.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Договор роли — не код. Это четыре строки: что роль принимает, что возвращает, по каким правилам проверяет себя и когда прекращает работу. Инструмент — только описанное разрешённое действие, не свободный доступ к аккаунту.' },
        { heading: 'Три безопасных маршрута', body: 'Normal: разрешённые данные → черновик → QA → внутренний отчёт. Missing-data: вернуть MISSING_DATA с пробелами. External-action: вернуть APPROVAL_REQUEST и не выполнять действие. Согласие и приватность входят в договор инструмента.' },
      ],
      practice: ['Сделай за 30 минут: заполни карточки Coordinator, Specialist и QA: вход, выход, правила, стоп.', 'Добавь три маршрута: normal, missing-data, external-action и итог каждого.'],
      artifactChecklist: ['Нет доступа «ко всем данным» или поручения «сделай всё».', 'Missing-data возвращает MISSING_DATA, а не выдуманный факт.', 'External-action заканчивается APPROVAL_REQUEST до отправления, изменения или удаления.'],
      quiz: { question: 'Что вернуть при запросе отправить клиенту сообщение?', answers: [{ id: 'approval-request', text: 'APPROVAL_REQUEST с описанием действия и владельцем решения.', correct: true }, { id: 'send-now', text: 'Сразу отправить вежливый черновик.', correct: false }] },
      nextStep: 'Завтра подготовь двенадцать безопасных проверочных случаев до любого запуска.', sourceIds: ['mcp-spec', 'openai-hitl', 'owasp-agentic', 'nist-genai-profile'],
    },
    {
      id: 'build-evals', slug: 'build-evals', title: 'Качество до запуска',
      outcome: 'Ты подготовишь 12 fixtures: четыре normal, четыре edge и четыре prohibited с критериями.',
      retrieval: 'Вспомни: что возвращает система при нехватке данных и внешнем действии?',
      lifeExample: { body: 'Новый трафарет проверяют на бумаге: обычный контур, сложный изгиб и то, чего делать нельзя. Это не доказывает идеальность татуировки, но замечает риск до клиента. Так же заранее готовят короткие тестовые карточки для процесса.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Fixture — безопасный заранее описанный вход с ожидаемым наблюдаемым результатом. Цикл: fixtures → критерии → несколько запусков → разбор. Повторяемость — достижение порога качества в серии похожих запусков, а не одинаковый текст символ в символ.' },
        { heading: 'Не верим красивому тексту', body: 'Проверяй исход, след выполнения и стоп-правило, а не уверенный тон. Детерминированная проверка маршрута и реальный интеграционный прогон отвечают на разные вопросы. До эмуляции не дают высокорисковый инструмент.' },
      ],
      practice: ['Сделай за 30 минут: выпиши 12 fixtures: 4 normal, 4 edge, 4 prohibited; добавь ожидаемый статус и критерий.', 'Используй только синтетические или разрешённые публичные входы; не вставляй клиентские тексты, номера, ключи или договоры.'],
      artifactChecklist: ['Есть 12 случаев и все три группы.', 'У каждого есть статус: INTERNAL_BRIEF, MISSING_DATA или APPROVAL_REQUEST.', 'Prohibited проверяют отказ от внешнего действия, не обход запрета.'],
      quiz: { question: 'Что лучше проверять в evaluation?', answers: [{ id: 'outcome-and-trace', text: 'Исход, след выполнения и соблюдение правила.', correct: true }, { id: 'confident-tone', text: 'Длину и уверенный тон черновика.', correct: false }] },
      nextStep: 'Завтра зафиксируй три прогона в Run Ledger и сравни их с базовой точкой.', sourceIds: ['openai-evals', 'anthropic-evals', 'openai-testing', 'agentbench', 'toolemu'],
    },
    {
      id: 'keep-run-ledger', slug: 'keep-run-ledger', title: 'Следы, а не красивые отчёты',
      outcome: 'Ты заведёшь Run Ledger для трёх безопасных прогонов: результат, время, источник, сбой и решение.',
      retrieval: 'Вспомни: почему fixtures нужны до запуска, а не после красивого результата?',
      lifeExample: { body: 'Кухонный талон показывает заказ, время, исполнителя и возврат. «Всё нормально» бесполезно, если блюдо вернули. Такая короткая таблица трёх проб показывает фактический ход работы.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Run Ledger хранит минимум: ID запуска, fixture, дату и время, статус, минуты, публичные источники, сбой и следующее решение. Он не хранит клиентские переписки, телефоны, секреты, пароли или полный рабочий артефакт.' },
        { heading: 'Локальная репетиция на столе', body: 'Сделай один наблюдаемый прогон без сервисов: 1) положи рядом свои role cards и route map; 2) возьми один synthetic или public fixture; 3) включи таймер; 4) сам пройди по стрелкам и запиши фактический результат каждой роли; 5) при нехватке данных остановись на MISSING_DATA, при неясности — REVIEW_REQUIRED; 6) запиши реальное число минут, итоговый статус и стоп-состояние. Повтори так максимум ещё два раза с другими безопасными fixtures; не заполняй журнал выдуманными результатами.' },
        { heading: 'Сравнение, а не обещание', body: 'Экономический результат — гипотеза. Сравни три прогона с базовой точкой человека по времени, стоимости, качеству и риску. Три безопасные пробы не доказывают доход, автономность или готовность к production.' },
      ],
      practice: ['Сделай за 30 минут: проведи один локальный прогон по role cards и route map на одном synthetic/public fixture, включив таймер и не подключая сервисы.', 'Если есть время, повтори максимум ещё два прогона с другими безопасными fixtures. Для каждой реально проведённой строки оставь fixture ID, статус, минуты, источники, сбой или «не найден», решение.'],
      artifactChecklist: ['Есть хотя бы одна строка с фактическими минутами, результатом и стоп-состоянием; пустые будущие строки честно остаются пустыми.', 'Каждая заполненная строка связана с конкретным synthetic/public fixture ID и маршрутом ролей.', 'Нет клиентских текстов, персональных данных, ключей, паролей, сервисных подключений или полного черновика.'],
      quiz: { question: 'Что является доказательством локального прогона?', answers: [{ id: 'actual-run', text: 'Фактические минуты, результат и стоп-состояние по конкретному fixture.', correct: true }, { id: 'invented-average', text: 'Правдоподобная средняя цифра без проведённого прогона.', correct: false }] },
      nextStep: 'Завтра разложи риски по матрице и определи, где нужен стоп-кран владельца.', sourceIds: ['openai-tracing', 'nist-ai-rmf', 'nist-genai-profile', 'anthropic-evals'],
    },
    {
      id: 'set-approval-gates', slug: 'set-approval-gates', title: 'Полномочия и стоп-кран',
      outcome: 'Ты создашь risk matrix и пакет APPROVAL_REQUEST для внешних или необратимых действий.',
      retrieval: 'Вспомни Run Ledger: какие метаданные он хранит, а что туда не попадает?',
      lifeExample: { body: 'Стажёр может подготовить платёжное поручение, но не отправляет деньги. Владелец видит сумму, получателя, причину и риск, затем решает. Полномочие — заранее видимая граница, а не доверие к красивому тексту.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Risk matrix сопоставляет действие с последствиями и решением: только черновик, остановить и уточнить или запросить одобрение. Сообщение, реклама, CRM, запись, платёж и изменение сайта в курсе агентом не исполняются. Стоп-правила и action gates запрещают удаление клиентских, бизнес- и чужих данных, опубликованных материалов и любых иных данных; исключение в будущей cloud-модели — только собственная запись учебного прогресса вошедшего ученика, не удаляемая этим уроком.' },
        { heading: 'Пакет на одобрение', body: 'APPROVAL_REQUEST содержит действие, цель, затронутые данные, внешний эффект, источник запроса, альтернативу «не делать» и владельца решения. Если пакет неполный или риск неясен, статус REVIEW_REQUIRED. Одобрение нужно до действия.' },
      ],
      practice: ['Сделай за 30 минут: заполни risk matrix минимум для пяти действий: сообщение, реклама, CRM, запись, платёж, сайт или удаление.', 'Создай пустой шаблон APPROVAL_REQUEST без реальных клиентских данных и назови владельца решения.'],
      artifactChecklist: ['У каждого действия есть internal draft only, REVIEW_REQUIRED или APPROVAL_REQUEST.', 'У внешнего или необратимого действия нет пути «выполнить автоматически».', 'Шаблон содержит цель, последствия, данные, альтернативу и владельца.'],
      quiz: { question: 'Когда нужен APPROVAL_REQUEST?', answers: [{ id: 'before-impact', text: 'До действия с внешним или необратимым эффектом.', correct: true }, { id: 'after-impact', text: 'После действия, чтобы сохранить отчёт.', correct: false }] },
      nextStep: 'Завтра собери Blueprint и прими решение только о безопасном shadow pilot.', sourceIds: ['openai-hitl', 'mcp-spec', 'owasp-agentic', 'nist-ai-rmf'],
    },
    {
      id: 'run-shadow-pilot', slug: 'run-shadow-pilot', title: 'Пилот без ставки всей студии',
      outcome: 'Ты соберёшь Agent Org Blueprint v1 и shadow-pilot decision card без production-прав.',
      retrieval: 'Вспомни: что обязан показать APPROVAL_REQUEST до решения владельца?',
      lifeExample: { body: 'Перед изменением живого процесса студия репетирует рядом с обычной работой: старый порядок главный, новый сравнивает черновики. Как пробная раскладка эскиза не заменяет процедуру, такая репетиция не заменяет реальную работу.' },
      sections: [
        { heading: 'Разбираем по-простому', body: 'Agent Org Blueprint v1 собирает Process Passport, role cards, route map, 12 fixtures, Run Ledger, risk matrix, approval policy и решение по пилоту. Shadow pilot берёт только разрешённые публичные или подготовленные данные и выпускает внутренний черновик или APPROVAL_REQUEST.' },
        { heading: 'Локальная репетиция и сравнение', body: 'Положи рядом свои role cards, route map и Run Ledger из дня 5. Возьми один synthetic/public fixture и проведи тот же локальный проход: включи таймер, пройди роли на бумаге, остановись на MISSING_DATA или REVIEW_REQUIRED, если это требуется маршрутом, и запиши фактические минуты, результат и стоп-состояние. Можно провести максимум три таких прогона всего; если реальных строк нет, decision card должен сказать stop или revise design, а не сравнивать выдуманные цифры.' },
        { heading: 'Решение на день семь', body: 'В decision card сравни только имеющиеся фактические строки с baseline: время, критерий качества и риск. Перечисли неразрешённые риски и выбери continue shadow pilot, revise design или stop. Это решение о следующем безопасном опыте, не о production, доходе или безошибочности.' },
      ],
      practice: ['Сделай за 30 минут: собери Agent Org Blueprint v1 из восьми артефактов и пометь отсутствующее REVIEW_REQUIRED.', 'Проведи или используй максимум три фактических локальных прогона из дня 5 и заполни decision card: baseline, реальные минуты/результаты/стоп-состояния, риски, решение и владелец. Не подключай сервисы и не выдавай права.'],
      artifactChecklist: ['Blueprint включает Passport, role cards, route map, 12 fixtures, Ledger, matrix, policy и decision card.', 'Decision card сравнивает baseline только с фактическими строками; при отсутствии строк выбирает stop или revise design, а не выдумывает сравнение.', 'Пилот read-only/draft-only: без сообщений, рекламы, CRM, записи, платежей, сайта и удаления.'],
      quiz: { question: 'Что доказывает успешный shadow pilot?', answers: [{ id: 'limited-evidence', text: 'Только результаты ограниченной безопасной проверки по критериям.', correct: true }, { id: 'production-ready', text: 'Что система безошибочна и готова заменить живой процесс.', correct: false }] },
      nextStep: 'Сохрани личный артефакт вне приложения, обсуди decision card с владельцем и запрашивай отдельное одобрение перед любым подключением.', sourceIds: ['openai-agent-guide', 'anthropic-multi-agent', 'openai-evals', 'openai-hitl', 'nist-genai-profile'],
    },
  ],
  references: [
    { slug: 'course-contract', title: 'Контракт курса', body: 'Семь дней ведут к Agent Org Blueprint v1 для одного ограниченного процесса. Оценка урока фиксирует учебный прогресс, не сертификацию и не работоспособность бизнеса. Studio Intelligence Brief остаётся read-only/draft-only.' },
  ],
  sources: [
    { id: 'openai-agent-guide', title: 'A Practical Guide to Building Agents', author: 'OpenAI', publishedAt: 'Apr 2025', sourceType: 'Официальное практическое руководство', rule: 'Начинать с малого сценария, ясных инструкций и guardrails.', url: 'https://cdn.openai.com/business-guides-and-resources/a-practical-guide-to-building-agents.pdf', accessedAt: '2026-08-31', usedFor: 'Выбор процесса, компоненты агента и границы.' },
    { id: 'anthropic-effective-agents', title: 'Building Effective Agents', author: 'Anthropic', publishedAt: 'Dec 2024', sourceType: 'Инженерная практика', rule: 'Отличать workflow от агента и начинать с простой композиции.', url: 'https://www.anthropic.com/engineering/building-effective-agents', accessedAt: '2026-08-31', usedFor: 'Выбор процесса и роли.' },
    { id: 'openai-orchestration', title: 'Agent orchestration', author: 'OpenAI', publishedAt: 'Без даты; проверено 2026-08-31', sourceType: 'Официальная SDK-документация', rule: 'Различать manager-as-tools и handoff как маршруты.', url: 'https://openai.github.io/openai-agents-python/multi_agent/', accessedAt: '2026-08-31', usedFor: 'Маршруты между ролями.' },
    { id: 'anthropic-multi-agent', title: 'How we built our multi-agent research system', author: 'Anthropic', publishedAt: 'Jun 2025', sourceType: 'Производственный полевой отчёт', rule: 'Многоагентность имеет стоимость и ограничения.', url: 'https://www.anthropic.com/engineering/multi-agent-research-system', accessedAt: '2026-08-31', usedFor: 'Ограничения делегирования и пилота.' },
    { id: 'openai-evals', title: 'Working with evals', author: 'OpenAI', publishedAt: 'Без даты; проверено 2026-08-31', sourceType: 'Официальная документация', rule: 'Описывать fixtures, graders и повторную оценку без привязки к меняющемуся API.', url: 'https://developers.openai.com/api/docs/guides/evals', accessedAt: '2026-08-31', usedFor: 'Платформенно-нейтральный evaluation loop.' },
    { id: 'anthropic-evals', title: 'Demystifying Evals for AI Agents', author: 'Anthropic', publishedAt: 'Jan 2026', sourceType: 'Инженерная практика', rule: 'Смотреть на outcome и trace серии испытаний, а не на убедительный текст.', url: 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents', accessedAt: '2026-08-31', usedFor: 'Fixtures и Run Ledger.' },
    { id: 'openai-testing', title: 'Testing', author: 'OpenAI', publishedAt: 'Без даты; проверено 2026-08-31', sourceType: 'Официальная SDK-документация', rule: 'Отличать детерминированный тест маршрута от интеграционного прогона.', url: 'https://openai.github.io/openai-agents-python/testing/', accessedAt: '2026-08-31', usedFor: 'Граница проверок.' },
    { id: 'openai-tracing', title: 'Tracing', author: 'OpenAI', publishedAt: 'Без даты; проверено 2026-08-31', sourceType: 'Официальная SDK-документация', rule: 'Сохранять нужный след запуска и минимизировать данные в логах.', url: 'https://openai.github.io/openai-agents-python/tracing/', accessedAt: '2026-08-31', usedFor: 'Поля Run Ledger.' },
    { id: 'openai-hitl', title: 'Human in the loop', author: 'OpenAI', publishedAt: 'Без даты; проверено 2026-08-31', sourceType: 'Официальная SDK-документация', rule: 'Approve, reject или pause нужны до существенного действия.', url: 'https://openai.github.io/openai-agents-python/human_in_the_loop/', accessedAt: '2026-08-31', usedFor: 'Approval gates.' },
    { id: 'mcp-spec', title: 'Model Context Protocol Specification', author: 'Model Context Protocol', publishedAt: '2025-03-26', sourceType: 'Спецификация', rule: 'Описывать инструмент, согласие, приватность и безопасность контрактом.', url: 'https://modelcontextprotocol.io/specification/2025-03-26/index', accessedAt: '2026-08-31', usedFor: 'Договоры и внешние действия.' },
    { id: 'nist-ai-rmf', title: 'AI Risk Management Framework 1.0', author: 'NIST', publishedAt: 'Jan 2023', sourceType: 'Стандарт', rule: 'Управлять риском через Govern, Map, Measure и Manage с human oversight.', url: 'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf', accessedAt: '2026-08-31', usedFor: 'Passport, matrix и oversight.' },
    { id: 'nist-genai-profile', title: 'Generative AI Profile', author: 'NIST', publishedAt: 'Jul 2024', sourceType: 'Профиль NIST', rule: 'Рассматривать риски генеративного ИИ на всём жизненном цикле.', url: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence', accessedAt: '2026-08-31', usedFor: 'Риски данных и пилота.' },
    { id: 'owasp-agentic', title: 'Securing Agentic Applications Guide 1.0', author: 'OWASP', publishedAt: 'Jul 2025', sourceType: 'Отраслевое руководство по безопасности', rule: 'Моделировать угрозы и меры; это не закон и не замена владельцу.', url: 'https://genai.owasp.org/resource/securing-agentic-applications-guide-1-0/', accessedAt: '2026-08-31', usedFor: 'Стоп-правила и доступы.' },
    { id: 'agentbench', title: 'AgentBench: Evaluating LLMs as Agents', author: 'Liu et al.', publishedAt: 'Aug 2023', sourceType: 'Исследовательская статья', rule: 'Интерактивного агента нельзя оценить одной репликой.', url: 'https://arxiv.org/abs/2308.03688', accessedAt: '2026-08-31', usedFor: 'Серия fixtures.' },
    { id: 'toolemu', title: 'Identifying the Risks of LM Agents with an LM-Emulated Sandbox', author: 'Ruan et al.', publishedAt: 'Sep 2023', sourceType: 'Исследовательская статья', rule: 'Не давать рискованные инструменты до эмуляции и проверки.', url: 'https://arxiv.org/abs/2309.15817', accessedAt: '2026-08-31', usedFor: 'Prohibited fixtures и shadow pilot.' },
  ],
};
